def create_preset_data_en(
    preset_name: str, 
    name: str, 
    gender: str, 
    age: int, 
    residence: str, 
    languages: str, 
    personality: str, 
    speech_style: str,
    appearance: str,
    hobbies: str,
    signature_lines: str,
    conversation_style: str,
    goals: str,
    response_by_user_actions: str
):
    return {
        "preset_name": preset_name,
        "name": name,
        "gender": gender,
        "age": age,
        "residence": residence,
        "languages": languages,
        "personality": personality,
        "speech_style": speech_style,
        "appearance": appearance,
        "hobbies": hobbies,
        "signature_lines": signature_lines,
        "conversation_style": conversation_style,
        "goals": goals,
        "response_by_user_actions": response_by_user_actions
    }

def create_preset_data_ko(
    preset_name: str, 
    name: str, 
    gender: str, 
    age: int, 
    residence: str, 
    languages: str, 
    personality: str, 
    speech_style: str,
    appearance: str,
    hobbies: str,
    signature_lines: str,
    conversation_style: str,
    goals: str,
    response_by_user_actions: str
):
    return {
        "preset_name_korean": preset_name,
        "name_korean": name,
        "gender_korean": gender,
        "age_korean": age,
        "residence_korean": residence,
        "languages_korean": languages,
        "personality_korean": personality,
        "speech_style_korean": speech_style,
        "appearance_korean": appearance,
        "hobbies_korean": hobbies,
        "signature_lines_korean": signature_lines,
        "conversation_style_korean": conversation_style,
        "goals_korean": goals,
        "response_by_user_actions_korean": response_by_user_actions
    }

def create_preset_data_ja(
    preset_name: str, 
    name: str, 
    gender: str, 
    age: int, 
    residence: str, 
    languages: str, 
    personality: str, 
    speech_style: str,
    appearance: str,
    hobbies: str,
    signature_lines: str,
    conversation_style: str,
    goals: str,
    response_by_user_actions: str
):
    return {
        "preset_name_japanese": preset_name,
        "name_japanese": name,
        "gender_japanese": gender,
        "age_japanese": age,
        "residence_japanese": residence,
        "languages_japanese": languages,
        "personality_japanese": personality,
        "speech_style_japanese": speech_style,
        "appearance_japanese": appearance,
        "hobbies_japanese": hobbies,
        "signature_lines_japanese": signature_lines,
        "conversation_style_japanese": conversation_style,
        "goals_japanese": goals,
        "response_by_user_actions_japanese": response_by_user_actions
    }

def create_preset_data_zh_cn(
    preset_name: str, 
    name: str, 
    gender: str, 
    age: int, 
    residence: str, 
    languages: str, 
    personality: str, 
    speech_style: str,
    appearance: str,
    hobbies: str,
    signature_lines: str,
    conversation_style: str,
    goals: str,
    response_by_user_actions: str
):
    return {
        "preset_name_chinese_simplified": preset_name,
        "name_chinese_simplified": name,
        "gender_chinese_simplified": gender,
        "age_chinese_simplified": age,
        "residence_chinese_simplified": residence,
        "languages_chinese_simplified": languages,
        "personality_chinese_simplified": personality,
        "speech_style_chinese_simplified": speech_style,
        "appearance_chinese_simplified": appearance,
        "hobbies_chinese_simplified": hobbies,
        "signature_lines_chinese_simplified": signature_lines,
        "conversation_style_chinese_simplified": conversation_style,
        "goals_chinese_simplified": goals,
        "response_by_user_actions_chinese_simplified": response_by_user_actions
    }

def create_preset_data_zh_tw(
    preset_name: str, 
    name: str, 
    gender: str, 
    age: int, 
    residence: str, 
    languages: str, 
    personality: str, 
    speech_style: str,
    appearance: str,
    hobbies: str,
    signature_lines: str,
    conversation_style: str,
    goals: str,
    response_by_user_actions: str
):
    return {
        "preset_name_chinese_traditional": preset_name,
        "name_chinese_traditional": name,
        "gender_chinese_traditional": gender,
        "age_chinese_traditional": age,
        "residence_chinese_traditional": residence,
        "languages_chinese_traditional": languages,
        "personality_chinese_traditional": personality,
        "speech_style_chinese_traditional": speech_style,
        "appearance_chinese_traditional": appearance,
        "hobbies_chinese_traditional": hobbies,
        "signature_lines_chinese_traditional": signature_lines,
        "conversation_style_chinese_traditional": conversation_style,
        "goals_chinese_traditional": goals,
        "response_by_user_actions_chinese_traditional": response_by_user_actions
    }